import { config } from "dotenv"
config();

export const DEFAULT_USER_CREDENTIALS = {
  USERNAME: "admin",
  PASSWORD: process.env.DEFAULT_USER_PASSWORD,
  NAME: "ashwin si"
}

export const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  NOT_ALLOWED: 403,
}